# Etiquetado de Componentes Conexos

In [13]:
import cv2
import numpy as np

In [14]:
imagen = cv2.imread("img/tornillos3.png", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)

-1

In [15]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 18 Etiquetas: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[    0     0   264   246 51811]
 [  222     2    42   173  4648]
 [  226     9     3     6     9]
 [  188    81     3     3     4]
 [   29    82   191   138  8433]
 [  204    82     1     1     1]
 [  120   129     1     1     1]
 [   99   133     1     1     1]
 [  227   137     4     3     5]
 [   79   146     3     1     3]
 [   67   150     3     1     3]
 [   62   154     1     1     1]
 [   25   158     1     1     1]
 [   62   158     3     2     3]
 [   29   165     1     1     1]
 [   42   179     5     4    16]
 [   43   185     1     2     2]
 [   37   189     1     1     1]] Centroides: [[123.16266816 119.88382776]
 [245.65017212  96.03334768]
 [226.88888889  11.22222222]
 [189.          82.25      ]
 [119.91390964 153.11490573]
 [204.          82.        ]
 [120.         129.        ]
 [ 99.         133.        ]


## De la documentación de OpenCV
### connectedComponentsWithStats
#### Parameters
- image	the 8-bit single-channel image to be labeled
- labels	destination labeled image
- stats	statistics output for each label, including the background label. Statistics are accessed via stats(label, COLUMN) where COLUMN is one of ConnectedComponentsTypes, selecting the statistic. The data type is CV_32S.
- centroids	centroid output for each label, including the background label. Centroids are accessed via centroids(label, 0) for x and centroids(label, 1) for y. The data type CV_64F.
- connectivity	8 or 4 for 8-way or 4-way connectivity respectively
- ltype	output image label type. Currently CV_32S and CV_16U are supported.

---

Los 'stats' están definidos por los siguientes tipos:
- CC_STAT_LEFT 
Python: cv.CC_STAT_LEFT
The leftmost (x) coordinate which is the inclusive start of the bounding box in the horizontal direction.
- CC_STAT_TOP 
Python: cv.CC_STAT_TOP
The topmost (y) coordinate which is the inclusive start of the bounding box in the vertical direction.
- CC_STAT_WIDTH 
Python: cv.CC_STAT_WIDTH
The horizontal size of the bounding box.
- CC_STAT_HEIGHT 
Python: cv.CC_STAT_HEIGHT
The vertical size of the bounding box.
- CC_STAT_AREA 
Python: cv.CC_STAT_AREA
The total area (in pixels) of the connected component.

In [17]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 100:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()